name: Fetch AWS Weather Data Hourly

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간마다 실행

jobs:
  fetch-aws-data:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 필요 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # 데이터 가져오는 스크립트 실행
      - name: Fetch AWS Data
        run: python hw8/fetch_data.py

      # 리포지토리의 최신 상태 가져오기 (충돌 방지)
      - name: Pull latest changes
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "2024sap"
          git pull origin main

      # 데이터 처리 및 저장
      - name: Save Data
        run: |
          if [ -f "path/to/your/file.csv" ]; then
              python -c "
import pandas as pd
df = pd.read_csv('new_data.csv', index_col=0, parse_dates=True)
existing_df = pd.read_csv('path/to/your/file.csv', index_col=0, parse_dates=True)
merged_df = pd.concat([existing_df, df], axis=0)
merged_df = merged_df[~merged_df.index.duplicated(keep='last')]
merged_df.sort_index(inplace=True)
merged_df.to_csv('path/to/your/file.csv')
print('Data has been saved to path/to/your/file.csv.')
"
          else
              cp new_data.csv path/to/your/file.csv
              echo "Data has been saved to path/to/your/file.csv."
          fi

      # GitHub Actions 로그에 알림 메시지 출력
      - name: Notify in GitHub Actions Log
        run: echo "데이터 왔다: Jeonju의 기상 데이터 받아라~"

      # 새로운 데이터를 리포지토리에 커밋
      - name: Commit and push data
        run: |
          git config --local user.email "guaum12@naver.com"
          git config --local user.name "2024sap"
          git add .

          # 데이터가 변경되었는지 확인하는 로그 추가
          git diff --cached --quiet && echo "No changes to commit" || (
            git commit -m "Add hourly AWS weather data" && echo "Changes committed"
          )

          # 변경 사항 푸시
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

